In [1]:
import numpy as np

In [2]:
temp_y = np.array([4, 3, 4, 7])
temp = np.array([[1, 2],[1, 3], [1, 4]])

In [3]:
X = np.array([[1, 2], [2, 3], [4, 5], [3, 6]])
y = np.array([3, 4, 5, 6])
bias = 0.5
w = np.array([1, 1])

In [4]:
w_b = np.hstack((w, bias))
w_b

array([1. , 1. , 0.5])

In [5]:
X.T

array([[1, 2, 4, 3],
       [2, 3, 5, 6]])

In [17]:
def linear_regresion(X, w, bias):
    """
    Function linear regression
    X - array (nxm) - n objects, m parametrs
    w - regression coefficients? m elements
    bias - scalar
    
    return y_pred, n elements
    """
    X_b = np.hstack((X, np.ones((X.shape[0], 1))))
    w_b = np.hstack((w, bias))
    return np.matmul(X_b, w_b)

In [18]:
linear_regresion(X, w, bias)

array([3.5, 5.5, 9.5, 9.5])

In [11]:
def loss(y_pred, y):
    """
    Loss function
    return sum(y_pred*y_pred - y*y) / (n*2)
    n - len(y)
    """
    return np.sum(np.power(y_pred - y, 2)) / len(y) / 2
        

In [2]:
def analytic_solution(X, y):
    """
    Function linear regression
    X - array (nxm) - n objects, m parametrs

    returns array m-features and bias
    """
    
    X_b = np.hstack((X, np.ones((X.shape[0], 1))))
    w = np.matmul(np.linalg.inv(np.matmul(X_b.T, X_b)), np.matmul(X_b.T, y))
    # w1 = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y
    return w

In [ ]:
def gradient_descent(X, y, w, bias, learning_rate):
    """
    PErfoms one step gradint descent
    """
    m = len(y)
    y_pred = linear_regresion(X, w, bias)
    error = y_pred - y
    gradient = np.matmul(X.T, error) / m
    w = w - learning_rate * gradient
    return w

In [9]:
    X = np.array([[1, 2], [2, 3], [4, 5], [3, 6]])
    y = np.array([3, 4, 5, 6])
    
    # Выполнение линейной регрессии
    theta = linear_regression(X, y)
    print("Коэффициенты линейной регрессии:", theta)

Коэффициенты линейной регрессии: [-0.14285714  0.78571429  1.71428571]


In [12]:
loss(temp_y, y)

0.5