In [63]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn import preprocessing
from copy import deepcopy

In [4]:
file_name = "Housing.csv"
path = ".\data"
path_data = os.path.join(path, file_name)

In [5]:
housing_data_df  = pd.read_csv(path_data)

In [6]:
housing_data_df

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [7]:
# housing_data_df.dtypes

In [8]:
# housing_data_df.isnull().sum()

In [9]:
# plt.scatter(housing_data_df["area"], housing_data_df["price"])

In [10]:
# sns.scatterplot(x='area', y='price', hue='bedrooms', palette='Set2', data=housing_data_df)

In [11]:
# temp_y = np.array([4, 3, 4, 7])
# temp = np.array([[1, 2],[1, 3], [1, 4]])

In [12]:
# X = np.array([[1, 2], [2, 3], [4, 5], [3, 6]])
# y = np.array([3, 4, 5, 6])
# bias = 0.5
# w = np.array([1, 1])

In [13]:
# w_b = np.hstack((w, bias))
# w_b

In [14]:
# X.T

In [15]:
def linear_regresion(X, w, bias):
    """
    Function linear regression
    X - array (nxm) - n objects, m parametrs
    w - regression coefficients? m elements
    bias - scalar
    
    return y_pred, n elements
    """
    X_b = np.hstack((X, np.ones((X.shape[0], 1))))
    w_b = np.hstack((w, bias))
    return np.matmul(X_b, w_b)

In [16]:
def loss(y_pred, y):
    """
    Loss function
    return sum(y_pred*y_pred - y*y) / (n*2)
    n - len(y)
    """
    return np.sum(np.power(y_pred - y, 2)) / len(y) / 2
        

In [54]:
def gradient_descent(X, y, w, bias, learning_rate):
    """
    Perfoms one step gradint descent
    """
    X_b = np.hstack((X, np.ones((X.shape[0], 1))))
    w_b = np.hstack((w, bias))
    
    m = len(y)
    y_pred = linear_regresion(X, w, bias)
    error = y_pred - y
    gradient = np.matmul(X_b.T, error) / m
    w_b = w_b - learning_rate * gradient
    bias = w_b[-1]
    w = w_b[:-1]
    return w, bias

In [68]:
X = housing_data_df[["area", "bedrooms", "bathrooms"]].to_numpy()
scaler = preprocessing.StandardScaler().fit(X)
scaler.mean_, scaler.scale_

(array([5.15054128e+03, 2.96513761e+00, 1.28623853e+00]),
 array([2.16814915e+03, 7.37386427e-01, 5.02008423e-01]))

In [66]:
X

array([[7420,    4,    2],
       [8960,    4,    4],
       [9960,    3,    2],
       ...,
       [3620,    2,    1],
       [2910,    3,    1],
       [3850,    3,    1]], dtype=int64)

In [67]:
X_scaled = scaler.transform(X)
X_scaled

array([[ 1.04672629,  1.40341936,  1.42181174],
       [ 1.75700953,  1.40341936,  5.40580863],
       [ 2.21823241,  0.04727831,  1.42181174],
       ...,
       [-0.70592066, -1.30886273, -0.57018671],
       [-1.03338891,  0.04727831, -0.57018671],
       [-0.5998394 ,  0.04727831, -0.57018671]])

In [40]:
y = housing_data_df[["price"]].to_numpy().reshape(-1,)

In [ ]:
scaler_y = preprocessing.StandardScaler().fit(X)
scaler_y.mean_, scaler.scale_

In [41]:
w = np.random.random(X.shape[1])

In [42]:
bias = np.random.random()

In [62]:
w, bias = gradient_descent(X, y, w, bias, 0.01)
w, bias

(array([-7.54576012e+57, -3.74880854e+54, -1.65171072e+54]),
 -1.2445104826891758e+54)

In [17]:
def analytic_solution(X, y):
    """
    Function linear regression
    X - array (nxm) - n objects, m parametrs
    returns array m-features and bias
    """    
    X_b = np.hstack((X, np.ones((X.shape[0], 1))))
    w = np.matmul(np.linalg.inv(np.matmul(X_b.T, X_b)), np.matmul(X_b.T, y))
    # w1 = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y
    return w